### ISSUE TITLE
What does this offer over Minecraft Dev?

### ISSUE THREAD

**Issue by ryantheleach** [WeAthFoLD/SideOnlyChecker#5]
If this doesn't offer anything over Minecraft Dev, maybe you could help work on that project as well?

https://github.com/minecraft-dev/MinecraftDev

**Comment by WeAthFoLD** [comment]
Hi,
I'm aware of MinecraftDev before I started this plugin, but didn't know that the plugin provided similar SideOnly checking capabilities, since there is no feature list to refer to.

Having quick checked its code, I'd say the plugin probably covers a range wider than this plugin does now. I'll try using the plugin and play around with the feature.

**Comment by WeAthFoLD** [comment]
Having tried the plugin and checked the code in more detail, I'd say that despite some small issues, it's sideonly inspection is fine to use. However, I also noticed that the plugin is not in active developement for quite some months (https://github.com/minecraft-dev/MinecraftDev/issues/461).

I will polish this plugin further regardless (It's my first IJ plugin and there are still lots to learn!), and if MinecraftDev plugin resumes normal developement, I can hopefully contribute to it.

And to answer your original question:

1. This plugin exposes invalid SideOnly usages as compilation errors instead of code inspection errors.
2. One can use `@SupressWarnings("sideonly")` annotation on methods to ignore certain methods' sideonly checking, to allow a kind of valid runtime referencing (https://github.com/minecraft-dev/MinecraftDev/issues/474).
